name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: get name
        id: name
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
            path: "package.json"
            prop_path: "name"

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
            path: "package.json"
            prop_path: "version"

      - name: Set Environment Variables
        run: |
          echo "repositoryName=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo "majorVersionValue=`echo ${{ steps.version.outputs.prop }} | cut -d '.' -f 1`" >> $GITHUB_ENV
          echo "zipFile=${{ steps.name.outputs.prop }}-${{ steps.version.outputs.prop }}.zip" >> $GITHUB_ENV

      - name: Create Zip
        run: zip -r "$ZIP_NAME" . -x '.*'
        env:
          ZIP_NAME: "${{env.zipFile}}"

      - name: Create VPAI Package
        run: curl -sL "https://api.anatawa12.com/create-vpai/?repo=https%3A%2F%2Fsayabeans.github.io%2Fvpm%2Findex.json&package=${{ steps.name.outputs.prop }}&version=${{ env.majorVersionValue }}.x.x" > ${{ env.repositoryName }}-${{ env.majorVersionValue }}.x.x-installer.unitypackage

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: v${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.repositoryName }}-${{ env.majorVersionValue }}.x.x-installer.unitypackage
            package.json
